package nz.ac.aut.ense701.gui;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import nz.ac.aut.ense701.gameModel.Game;

/**
 *
 * @author taehyun Kim 1399548
 */
public class GameStartFrame extends JFrame {
    

    public GameStartFrame() {

        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        initComponents();
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gameStartBtn = new javax.swing.JPanel();
        GameTitle = new javax.swing.JLabel();
        playBtn = new javax.swing.JButton();
        exitBtn = new javax.swing.JButton();
        mainLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kiwi Avengers");
        setMaximumSize(new java.awt.Dimension(1280, 719));
        setMinimumSize(new java.awt.Dimension(1280, 719));
        setName("MenuF"); // NOI18N
        setPreferredSize(new java.awt.Dimension(772, 447));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        gameStartBtn.setToolTipText("");
        gameStartBtn.setMaximumSize(new java.awt.Dimension(1280, 719));
        gameStartBtn.setMinimumSize(new java.awt.Dimension(1280, 719));
        gameStartBtn.setOpaque(false);
        gameStartBtn.setPreferredSize(new java.awt.Dimension(833, 678));

        GameTitle.setFont(new java.awt.Font("Wide Latin", 1, 48)); // NOI18N
        GameTitle.setForeground(new java.awt.Color(102, 153, 0));
        GameTitle.setText("Kiwi Avengers");

        playBtn.setBackground(new java.awt.Color(255, 255, 255));
        playBtn.setFont(new java.awt.Font("SketchFlow Print", 1, 24)); // NOI18N
        playBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/start_btn2.png"))); // NOI18N
        playBtn.setToolTipText("");
        playBtn.setActionCommand("Game Start");
        playBtn.setBorderPainted(false);
        playBtn.setContentAreaFilled(false);
        playBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        playBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                playBtnMouseClicked(evt);
            }
        });
        playBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playBtnActionPerformed(evt);
            }
        });

        exitBtn.setFont(new java.awt.Font("SketchFlow Print", 1, 24)); // NOI18N
        exitBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/quit_btn.png"))); // NOI18N
        exitBtn.setBorderPainted(false);
        exitBtn.setContentAreaFilled(false);
        exitBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gameStartBtnLayout = new javax.swing.GroupLayout(gameStartBtn);
        gameStartBtn.setLayout(gameStartBtnLayout);
        gameStartBtnLayout.setHorizontalGroup(
            gameStartBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameStartBtnLayout.createSequentialGroup()
                .addGroup(gameStartBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gameStartBtnLayout.createSequentialGroup()
                        .addComponent(GameTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gameStartBtnLayout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(playBtn)))
                .addContainerGap(409, Short.MAX_VALUE))
        );
        gameStartBtnLayout.setVerticalGroup(
            gameStartBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameStartBtnLayout.createSequentialGroup()
                .addGroup(gameStartBtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gameStartBtnLayout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addComponent(GameTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(exitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(120, 120, 120)
                .addComponent(playBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(297, Short.MAX_VALUE))
        );

        getContentPane().add(gameStartBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, 880, 440));

        mainLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/main_frame.png"))); // NOI18N
        getContentPane().add(mainLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 719));
        mainLabel.getAccessibleContext().setAccessibleName("MenuBack");
        mainLabel.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void playBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_playBtnMouseClicked
        
    }//GEN-LAST:event_playBtnMouseClicked

    private void exitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBtnActionPerformed
        int exitBut = JOptionPane.showConfirmDialog(this, "Do you want to exit the game?", "Exit?",JOptionPane.OK_CANCEL_OPTION);
        if(exitBut == 0){
            System.exit(0);
        }
    }//GEN-LAST:event_exitBtnActionPerformed

    private void playBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playBtnActionPerformed
        initGame();
        this.setVisible(false);
    }//GEN-LAST:event_playBtnActionPerformed

    private void initGame(){
        // create the game object
        final Game game = new Game();
        // create the GUI for the game
        final KiwiCountUI  gui  = new KiwiCountUI(game);
    
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() 
            {
                gui.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GameTitle;
    private javax.swing.JButton exitBtn;
    private javax.swing.JPanel gameStartBtn;
    private javax.swing.JLabel mainLabel;
    private javax.swing.JButton playBtn;
    // End of variables declaration//GEN-END:variables
}
