/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nz.ac.aut.ense701.gui;

import javax.swing.JFrame;
import nz.ac.aut.ense701.gameModel.Game;

/**
 *
 * @author mcc7514
 */
public class GameInstruct extends javax.swing.JFrame {
    
    Game game;

    /**
     * Creates new form GameStoryInstruct
     */
    public GameInstruct() {
        initComponents();
        displayInstruction();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gameInstructionPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        gameInstrucText = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        gameObjectiveText = new javax.swing.JTextArea();
        gameInstructIcons2 = new javax.swing.JPanel();
        iconDisplay1 = new javax.swing.JLabel();
        iconDisplay2 = new javax.swing.JLabel();
        iconDisplay3 = new javax.swing.JLabel();
        iconDisplay4 = new javax.swing.JLabel();
        iconDisplay5 = new javax.swing.JLabel();
        iconDisplay6 = new javax.swing.JLabel();
        iconDisplay7 = new javax.swing.JLabel();
        iconDisplay9 = new javax.swing.JLabel();
        iconDisplay10 = new javax.swing.JLabel();
        iconDisplay11 = new javax.swing.JLabel();
        iconDisplay12 = new javax.swing.JLabel();
        iconDisplay13 = new javax.swing.JLabel();
        descField1 = new javax.swing.JLabel();
        descField2 = new javax.swing.JLabel();
        descField3 = new javax.swing.JLabel();
        descField4 = new javax.swing.JLabel();
        descField6 = new javax.swing.JLabel();
        descField5 = new javax.swing.JLabel();
        descField7 = new javax.swing.JLabel();
        descField9 = new javax.swing.JLabel();
        descField10 = new javax.swing.JLabel();
        descField11 = new javax.swing.JLabel();
        descField12 = new javax.swing.JLabel();
        descField13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        gameInstrucText.setEditable(false);
        gameInstrucText.setColumns(20);
        gameInstrucText.setFont(new java.awt.Font("Times New Roman Uni", 0, 14)); // NOI18N
        gameInstrucText.setRows(5);
        gameInstrucText.setAutoscrolls(false);
        gameInstrucText.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Instruction", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 1, 18), new java.awt.Color(0, 102, 153))); // NOI18N
        jScrollPane1.setViewportView(gameInstrucText);

        gameObjectiveText.setEditable(false);
        gameObjectiveText.setColumns(20);
        gameObjectiveText.setFont(new java.awt.Font("Times New Roman Uni", 0, 14)); // NOI18N
        gameObjectiveText.setRows(2);
        gameObjectiveText.setAutoscrolls(false);
        gameObjectiveText.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Objective", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 1, 18), new java.awt.Color(0, 102, 153))); // NOI18N
        jScrollPane2.setViewportView(gameObjectiveText);

        javax.swing.GroupLayout gameInstructionPanelLayout = new javax.swing.GroupLayout(gameInstructionPanel);
        gameInstructionPanel.setLayout(gameInstructionPanelLayout);
        gameInstructionPanelLayout.setHorizontalGroup(
            gameInstructionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameInstructionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gameInstructionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 835, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        gameInstructionPanelLayout.setVerticalGroup(
            gameInstructionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameInstructionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        gameInstructIcons2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Icons", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial Rounded MT Bold", 1, 18), new java.awt.Color(0, 102, 153))); // NOI18N

        iconDisplay1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/player_half.png"))); // NOI18N

        iconDisplay2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wellington-fixed_half.png"))); // NOI18N

        iconDisplay3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/auckland-fixed_half.png"))); // NOI18N

        iconDisplay4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/christchurch-fixed_half.png"))); // NOI18N

        iconDisplay5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bluff-fixed_half.png"))); // NOI18N

        iconDisplay6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/oamaru-fixed_half.png"))); // NOI18N

        iconDisplay7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/predator_half.png"))); // NOI18N

        iconDisplay9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/forest_half.png"))); // NOI18N

        iconDisplay10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/sand_half.png"))); // NOI18N

        iconDisplay11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/water_half.png"))); // NOI18N

        iconDisplay12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wetland_half.png"))); // NOI18N

        iconDisplay13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/scrub_half.png"))); // NOI18N

        descField1.setText("jLabel1");

        descField2.setText("jLabel1");

        descField3.setText("jLabel1");

        descField4.setText("jLabel1");

        descField6.setText("jLabel1");

        descField5.setText("jLabel1");

        descField7.setText("jLabel1");

        descField9.setText("jLabel1");

        descField10.setText("jLabel1");

        descField11.setText("jLabel1");

        descField12.setText("jLabel1");

        descField13.setText("jLabel1");

        javax.swing.GroupLayout gameInstructIcons2Layout = new javax.swing.GroupLayout(gameInstructIcons2);
        gameInstructIcons2.setLayout(gameInstructIcons2Layout);
        gameInstructIcons2Layout.setHorizontalGroup(
            gameInstructIcons2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gameInstructIcons2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(gameInstructIcons2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gameInstructIcons2Layout.createSequentialGroup()
                        .addComponent(iconDisplay6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(descField6, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gameInstructIcons2Layout.createSequentialGroup()
                        .addComponent(iconDisplay1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(descField1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gameInstructIcons2Layout.createSequentialGroup()
                        .addComponent(iconDisplay2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(descField2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gameInstructIcons2Layout.createSequentialGroup()
                        .addComponent(iconDisplay4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(descField4, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gameInstructIcons2Layout.createSequentialGroup()
                        .addComponent(iconDisplay3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(descField3, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gameInstructIcons2Layout.createSequentialGroup()
                        .addComponent(iconDisplay5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(descField5, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addGroup(gameInstructIcons2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gameInstructIcons2Layout.createSequentialGroup()
                        .addComponent(iconDisplay13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(descField13, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gameInstructIcons2Layout.createSequentialGroup()
                        .addComponent(iconDisplay11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(descField11, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gameInstructIcons2Layout.createSequentialGroup()
                        .addComponent(iconDisplay10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(descField10, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gameInstructIcons2Layout.createSequentialGroup()
                        .addComponent(iconDisplay12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(descField12, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gameInstructIcons2Layout.createSequentialGroup()
                        .addGroup(gameInstructIcons2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(iconDisplay9)
                            .addComponent(iconDisplay7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(gameInstructIcons2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(descField7, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(descField9, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(45, 45, 45))
        );
        gameInstructIcons2Layout.setVerticalGroup(
            gameInstructIcons2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gameInstructIcons2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gameInstructIcons2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(gameInstructIcons2Layout.createSequentialGroup()
                        .addGroup(gameInstructIcons2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(iconDisplay1)
                            .addGroup(gameInstructIcons2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(descField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(descField7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(gameInstructIcons2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(iconDisplay2)
                            .addComponent(descField2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(gameInstructIcons2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(gameInstructIcons2Layout.createSequentialGroup()
                                .addGroup(gameInstructIcons2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(iconDisplay3)
                                    .addComponent(descField3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(iconDisplay4))
                            .addComponent(descField4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(gameInstructIcons2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(iconDisplay5)
                            .addComponent(descField5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(gameInstructIcons2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(iconDisplay6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(descField6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(gameInstructIcons2Layout.createSequentialGroup()
                        .addGroup(gameInstructIcons2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(descField12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(gameInstructIcons2Layout.createSequentialGroup()
                                .addComponent(iconDisplay7)
                                .addGap(11, 11, 11)
                                .addGroup(gameInstructIcons2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gameInstructIcons2Layout.createSequentialGroup()
                                        .addGroup(gameInstructIcons2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(iconDisplay9)
                                            .addComponent(descField9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(gameInstructIcons2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(iconDisplay10)
                                            .addComponent(descField10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(gameInstructIcons2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(iconDisplay11, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(descField11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(61, 61, 61))
                                    .addComponent(iconDisplay12, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(61, 61, 61))
                    .addComponent(iconDisplay13)
                    .addComponent(descField13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gameInstructionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(gameInstructIcons2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(gameInstructionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gameInstructIcons2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void displayInstruction(){
        
        gameInstrucText.setText("Player starts off at any random position on the board and is able to move right left up or down each grid.\n" +
            "Each grid may have a certain item to collect and it is upto the player to decide whether they want to collect the item by picking it up. \n" +
            "There are 5 cities to visit in this game and they are Auckland,Wellington,Oamaru,Bluff and Christchurch.\n" +
            "Wellington is the safe house.\n" +
            "Each city has its own unique collectables.\n" +
            "If you land on a grid that has a predator your health decreases a little.\n" +
            "There are also health items to be collected these are to be picked up to heal the player.");
        gameObjectiveText.setText("The main objective of this game is to save the 5 cities in need by collecting the items to save the cities \n"+
                " which need fixing in each grid square");
        descField1.setText("Player Icon");
        descField2.setText("City- This is the capical city, Wellington");
        descField3.setText("City- This is the Auckland icon");
        descField4.setText("City- This is the Christchurch city");
        descField5.setText("City- This is the Bluff city");
        descField6.setText("City- This is the Oamaru city");
        descField7.setText("Predator - Landing on this icon will reduce health");
        descField9.setText("Land- Forest (stamina -2%)");
        descField10.setText("Land- Sand (stamina -1%)");
        descField11.setText("Land- Water (stamina -4%)");
        descField12.setText("Land- Wet Land (stamina -2.5%)");
        descField13.setText("Land- Scrub (stamina -3%)");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel descField1;
    private javax.swing.JLabel descField10;
    private javax.swing.JLabel descField11;
    private javax.swing.JLabel descField12;
    private javax.swing.JLabel descField13;
    private javax.swing.JLabel descField2;
    private javax.swing.JLabel descField3;
    private javax.swing.JLabel descField4;
    private javax.swing.JLabel descField5;
    private javax.swing.JLabel descField6;
    private javax.swing.JLabel descField7;
    private javax.swing.JLabel descField9;
    private javax.swing.JTextArea gameInstrucText;
    private javax.swing.JPanel gameInstructIcons2;
    private javax.swing.JPanel gameInstructionPanel;
    private javax.swing.JTextArea gameObjectiveText;
    private javax.swing.JLabel iconDisplay1;
    private javax.swing.JLabel iconDisplay10;
    private javax.swing.JLabel iconDisplay11;
    private javax.swing.JLabel iconDisplay12;
    private javax.swing.JLabel iconDisplay13;
    private javax.swing.JLabel iconDisplay2;
    private javax.swing.JLabel iconDisplay3;
    private javax.swing.JLabel iconDisplay4;
    private javax.swing.JLabel iconDisplay5;
    private javax.swing.JLabel iconDisplay6;
    private javax.swing.JLabel iconDisplay7;
    private javax.swing.JLabel iconDisplay9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
