package nz.ac.aut.ense701.gui;

import java.awt.Color;
import java.awt.Image;
import javafx.scene.layout.ColumnConstraintsBuilder;
import javax.swing.ImageIcon;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import nz.ac.aut.ense701.gameModel.City;
import nz.ac.aut.ense701.gameModel.CityType;
import nz.ac.aut.ense701.gameModel.Game;
import nz.ac.aut.ense701.gameModel.Occupant;
import nz.ac.aut.ense701.gameModel.PanelImageHandle;
import nz.ac.aut.ense701.gameModel.Terrain;

/*
 * Panel for representing a single GridSquare of the island on the GUI.
 * 
 * @author AS
 * @version 1.0 - created
 */

public class GridSquarePanel extends javax.swing.JPanel 
{
    /** 
     * Creates new GridSquarePanel.
     * @param game the game to represent
     * @param row the row to represent
     * @param column the column to represent
     */
    public GridSquarePanel(Game game,PanelImageHandle panelImage, int row, int column)
    {
        this.game   = game;
        this.panelImage = panelImage;
        this.row    = row;
        this.column = column;
        initComponents();
    }

    /**
     * Updates the representation of the grid square panel.
     */
    public void update()
    {

        boolean squareVisible = game.isVisible(row, column);
        boolean squareExplored = game.isExplored(row, column);

        lblText.setIcon(null);
        lblText.setBackground(null);

        if ( squareExplored || squareVisible )
        {
            Terrain terrain   = game.getTerrain(row, column);
            Occupant[] occ = game.getOccupants(row, column);
            boolean hasOccupant = game.hasOccupant(row, column);
            boolean hasPredator = game.hasPredator(row, column);
            boolean hasPlayer = game.hasPlayer(row,column);
            
            if(hasPlayer)
                setBorder(activeBorder);
            else
                setBorder(normalBorder);
            lblText.setIcon(panelImage.getIcon(terrain,occ, hasOccupant, hasPredator, hasPlayer));
        }
        else
        {
            lblText.setBackground(new Color(51,51,51));
            setBorder(normalBorder);
        }
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblText = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setLayout(new java.awt.BorderLayout());

        lblText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblText.setOpaque(true);
        add(lblText, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblText;
    // End of variables declaration//GEN-END:variables
    
    private Game game;
    private int row, column;
    private PanelImageHandle panelImage;
    
    private static final Border normalBorder = new LineBorder(Color.BLACK, 1);
    private static final Border activeBorder = new LineBorder(Color.RED, 3);
}
