package nz.ac.aut.ense701.gui;

import java.awt.Color;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import nz.ac.aut.ense701.gameModel.City;
import nz.ac.aut.ense701.gameModel.CityType;
import nz.ac.aut.ense701.gameModel.Game;
import nz.ac.aut.ense701.gameModel.Occupant;
import nz.ac.aut.ense701.gameModel.Terrain;

/*
 * Panel for representing a single GridSquare of the island on the GUI.
 * 
 * @author AS
 * @version 1.0 - created
 */

public class GridSquarePanel extends javax.swing.JPanel 
{
    /** 
     * Creates new GridSquarePanel.
     * @param game the game to represent
     * @param row the row to represent
     * @param column the column to represent
     */
    public GridSquarePanel(Game game, int row, int column)
    {
        this.game   = game;
        this.row    = row;
        this.column = column;
        initComponents();
    }

    /**
     * Updates the representation of the grid square panel.
     */
    public void update()
    {
        // get the GridSquare object from the world
        Terrain terrain   = game.getTerrain(row, column);
        boolean squareVisible = game.isVisible(row, column);
        boolean squareExplored = game.isExplored(row, column);
        boolean hasOccupant = game.hasOccupant(row, column);
        boolean hasPredator = game.hasPredator(row, column);
        boolean hasPlayer = game.hasPlayer(row,column);
        
        String imageFile = "";
        lblText.setIcon(null);
        
        switch ( terrain )
        {
            case SAND     : imageFile = "sand";break;
            case FOREST   : imageFile = "forest"; break;
            case WETLAND : imageFile = "wetland";break;
            case SCRUB : imageFile = "scrub";break;
            case WATER    : imageFile = "water";break;
            default  : imageFile = "ground";break;
        }
        
        if ( squareExplored || squareVisible )
        {
            // Set the text of the JLabel according to the occupant
            //lblText.setText(game.getOccupantStringRepresentation(row,column));
            // Set the colour. 
            if ( squareVisible && !squareExplored ) 
            {
                // When explored the colour is brighter
            }
            
            if(hasOccupant)
                imageFile += "-occupant";
            
            if(hasPredator)
                imageFile = "predator";
            
            Occupant[] occ = game.getOccupants(row, column);
            for(Occupant o : occ){
                if(o instanceof City){
                    City city = (City)o;
                    CityType cityType = city.getType();
                    switch(cityType){
                        case Auckland : imageFile = "auckland"; break;
                        case Christchurch : imageFile = "christchurch"; break;
                        case Bluff : imageFile = "bluff"; break;
                        case Oamaru : imageFile = "oamaru"; break;
                        case Wellington : imageFile = "wellington"; break;
                    }
                    if(city.isFixed()) imageFile += "-fixed";
                    break;
                }
            }
            
            if(hasPlayer){
                setBorder(activeBorder);
                imageFile = "player";
            }else{
                setBorder(normalBorder);
            }
            
            lblText.setIcon(getResizedIcon("src/images/"+imageFile+".png"));
        }
        else
        {
            //lblText.setText("");
            lblText.setBackground(new Color(51,51,51));
            setBorder(normalBorder);
        }
    }
    
    private ImageIcon getResizedIcon(String filelocation){
        ImageIcon imageIcon = new ImageIcon(filelocation); // load the image to a imageIcon
        Image image = imageIcon.getImage(); // transform it 
        Image newimg = image.getScaledInstance(65, 55,  java.awt.Image.SCALE_FAST); // scale it the smooth way  
        imageIcon = new ImageIcon(newimg);  // transform it back
        return imageIcon;
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblText = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setLayout(new java.awt.BorderLayout());

        lblText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblText.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblText.setOpaque(true);
        add(lblText, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblText;
    // End of variables declaration//GEN-END:variables
    
    private Game game;
    private int row, column;
    
    private static final Border normalBorder = new LineBorder(Color.BLACK, 1);
    private static final Border activeBorder = new LineBorder(Color.RED, 3);
}
